### ISSUE TITLE
Clone or download the repository

### ISSUE THREAD

**Issue by davidhoho** [JozefJarosciak/XenMinerWrapper#2]
Hello Jozef,
what do you mean Clone or download the repository?
I'm stuck
thank you
david

**Comment by JozefJarosciak** [comment]
First, ensure you have Git installed. If not, download and install it from [git-scm.com](https://git-scm.com/).

**Windows**:
Open Git Bash (usually found in the Start Menu after installing Git).
Navigate to the directory where you want to clone the repository using the cd command. For example:
bash
Copy code
cd C:\path\to\your\directory
Clone the repository using the following command:
bash
Copy code
git clone https://github.com/JozefJarosciak/XenMinerWrapper.git

**Macintosh**:
Open the Terminal application (found in /Applications/Utilities/).
Navigate to the directory where you want to clone the repository using the cd command. For example:
bash
Copy code
cd /path/to/your/directory
Clone the repository using the following command:
bash
Copy code
git clone https://github.com/JozefJarosciak/XenMinerWrapper.git

**Linux**:
Open a terminal window.
Navigate to the directory where you want to clone the repository using the cd command. For example:
bash
Copy code
cd /path/to/your/directory
Clone the repository using the following command:
bash
Copy code
git clone https://github.com/JozefJarosciak/XenMinerWrapper.git
After executing these steps on any of the operating systems, you should have a directory named XenMinerWrapper in your specified directory, which contains all the files from the repository.
