### ISSUE TITLE
New Update freezes XenMinerWrapper

### ISSUE THREAD

**Issue by hannescrypto** [JozefJarosciak/XenMinerWrapper#3]
Dear Jozef

I use your tool and i like it because of the nice UI and not having to open 10 windows.

But a Problem i see here is that your tool always lacks behind because of so many changes Jack does with his Github and miner.py.

So would it be much better so simplyfy this tool to bare minimum so it will always work

1.) grab miner.py from github
2.) change ETH Adresse
3.) make as many instances as we like count blocks found but with the search for "Found valid hash" counting this on every instance

So with these changes, jack can change what he wants and your tool should allways work and you/we are not lacking behind every update

Thanks so much for your work, i know python but sadly not good enough to change this my self ;-)

**Comment by kodiii** [comment]
me to the same problem on my macs

**Comment by hannescrypto** [comment]
i just coded on your tool a littlebit and changed some usefull things

1.) can now also get a txt file for miner.py location

2.) shows me cpu cores ans threads

3.) show me the cpu load and mem load (but i cannot get it updating, only updated on start 

4.) disabled hash tick

![image](https://github.com/JozefJarosciak/XenMinerWrapper/assets/127392108/0af57012-b202-495c-85a6-eb0281615b02)

**Comment by kodiii** [comment]
are you already able to run it? if so can you share it?

**Comment by hannescrypto** [comment]
no sadly it doesnt update the cpu load and mem load, its really difficult sadly

**Comment by JozefJarosciak** [comment]
I tried this as well, and no luck in python, not on windows, so I removed that eventually.

**Comment by kodiii** [comment]
can you please provide the version before this upgrade you made?

**Comment by hannescrypto** [comment]
hey guys i just uploaded my modded version to my github

would love to see Jozef implement my cores/threads and maybe cpu/mem load thing in your new version

https://github.com/hannescrypto/XenMinerWrapper_h

![image](https://github.com/JozefJarosciak/XenMinerWrapper/assets/127392108/f105f542-db61-4ed5-924f-39e9779e9a5b)

**Comment by hannescrypto** [comment]
hannescrypto modded version 
changes

1.) shows CPU cores/threads (and now you can select the threads not the cores)

2.) show CPU Load/Mem Load (sadly only update on Startup) 

3.) store all userfiles incl. Loaction of miner.py in userdata folder

4.) works with newest miner.py but weird output because of new colorscheme in miner.py

5.) made the window wider so no problems with the miner text splitet up in 2 rows





Date 21.09.2023

**Comment by JozefJarosciak** [comment]
Download the latest version, this problem is fixed now. Enjoy!
