### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by ominari** [JozefJarosciak/XenMinerWrapper#5]
Windows 11.  Running in Admin Command Prompt.  GUI pops up and after I fill out the required info I get this error.  Any advice?

C:\Users\Justin\Desktop\XenMinerWrapper-master>python xenminerwrapper.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Desktop\XenMinerWrapper-master\xenminerwrapper.py", line 120, in run_script
    process = subprocess.Popen([python_env, 'miner.py'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied

**Comment by JozefJarosciak** [comment]
Ensure that the path specified in the application is correct and that you have permission to execute it. If it's a system-wide Python installation, you might need elevated permissions to run it. Also, check miner.py: Ensure that miner.py is in the same directory as xenminerwrapper.py or provide an absolute path to it. And check antivirus or firewall Interference.

**Comment by JozefJarosciak** [comment]
this should be fixed now, download update:
https://twitter.com/jarosciak/status/1706498290227830895
