### ISSUE TITLE
location files for ETH and PYTHON didnt load up on next start

### ISSUE THREAD

**Issue by hannescrypto** [JozefJarosciak/XenMinerWrapper#7]
dear Jozef

like i told before i tried your new version (i like it ;-), but i found a bug which  worked on the first version but not now.

When you put in your ETH Address and Python loaction, in the previous version it got saved and you can close your tool and open up again and the text loaded up like before, but now its empty again.

Tried on Windows and Linux, both not working

best regards
hannes

**Comment by JozefJarosciak** [comment]
this is fixed now, download update:
https://twitter.com/jarosciak/status/1706498290227830895
