### ISSUE TITLE
miner.py not loading in new version under linux

### ISSUE THREAD

**Issue by hannescrypto** [JozefJarosciak/XenMinerWrapper#9]
hey Jozef

i just tried your new version,

under Linux the Miner.py is not downloaded

![image](https://github.com/JozefJarosciak/XenMinerWrapper/assets/127392108/c0e69e07-e800-4b84-8773-d4a26aad6683)

**Comment by hannescrypto** [comment]
and when i copy it from the xenminer github over to your xenminerwrapper folder this error comes up

![image](https://github.com/JozefJarosciak/XenMinerWrapper/assets/127392108/a761c39e-7d35-4b3c-a6a4-b39676cec343)

**Comment by hannescrypto** [comment]
hope it helps

i also pressed out a new version of my XenMinerLoader V1.1 ;-)

https://github.com/hannescrypto/XenMinerLoader

i like yours more than mine, but on your version its much harder i guess to keep up with the updates on jacks github site

**Comment by hannescrypto** [comment]
just found out the problem

you saved the miner.py in the new config.conf

![image](https://github.com/JozefJarosciak/XenMinerWrapper/assets/127392108/e3496784-80b4-448a-ad52-26ad4672e953)

**Comment by hannescrypto** [comment]
and on quick looking over the code you havent downloaded the real config.conf only miner.py, but as you know its super hard see whats going on here for me, only guesses from my side

hope it helped

**Comment by hannescrypto** [comment]
![image](https://github.com/JozefJarosciak/XenMinerWrapper/assets/127392108/f5a2dbf1-b83a-4187-a8c0-c7a17be043ee)

**Comment by JozefJarosciak** [comment]
Yes this is an issue since the last update of miner by Jack. He now moved
config section into dedicated config file. I'll fix this later.

**Comment by JozefJarosciak** [comment]
https://twitter.com/jarosciak/status/1706498290227830895
